# Generated by Django 3.1 on 2020-08-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlisBilgisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyatTL', models.PositiveSmallIntegerField()),
                ('tarih', models.DateField()),
                ('kilo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('aciklama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cikis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CikisSebebi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cinsiyet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Irk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Isletme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pazarlikci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=11)),
                ('adres', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Ticaret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyatTL', models.PositiveSmallIntegerField()),
                ('tarih', models.DateField()),
                ('cikis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.cikis')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.pazarlikci')),
            ],
        ),
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupeNo', models.CharField(max_length=10)),
                ('padokNo', models.CharField(max_length=10)),
                ('aciklama', models.CharField(max_length=200)),
                ('aktif', models.BooleanField(null=True)),
                ('alisBilgisi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.alisbilgisi')),
                ('cinsiyet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.cinsiyet')),
                ('irk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.irk')),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.isletme')),
            ],
        ),
        migrations.CreateModel(
            name='EskiKupeNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskiKupe', models.PositiveSmallIntegerField()),
                ('yeniKupe', models.PositiveSmallIntegerField()),
                ('tarih', models.DateField()),
                ('hayvan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.hayvan')),
            ],
        ),
        migrations.AddField(
            model_name='cikis',
            name='hayvan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.hayvan'),
        ),
        migrations.AddField(
            model_name='cikis',
            name='sebep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.cikissebebi'),
        ),
        migrations.CreateModel(
            name='AsiBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('asi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.asi')),
                ('hayvan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.hayvan')),
            ],
        ),
        migrations.AddField(
            model_name='alisbilgisi',
            name='pazarlikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Database.pazarlikci'),
        ),
    ]
