# Generated by Django 3.1 on 2020-09-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200831_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alisbilgisi',
            name='pazarlikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.pazarlikci'),
        ),
        migrations.AlterField(
            model_name='asibilgi',
            name='asi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.asi'),
        ),
        migrations.AlterField(
            model_name='asibilgi',
            name='hayvan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hayvan'),
        ),
        migrations.AlterField(
            model_name='cikis',
            name='hayvan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hayvan'),
        ),
        migrations.AlterField(
            model_name='cikis',
            name='sebep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.cikissebebi'),
        ),
        migrations.AlterField(
            model_name='eskikupeno',
            name='eskiKupe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eskikupeno',
            name='hayvan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hayvan'),
        ),
        migrations.AlterField(
            model_name='eskikupeno',
            name='yeniKupe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='alisBilgisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.alisbilgisi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='cinsiyet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.cinsiyet'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='irk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.irk'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='isletme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.isletme'),
        ),
        migrations.AlterField(
            model_name='ticaret',
            name='cikis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.cikis'),
        ),
        migrations.AlterField(
            model_name='ticaret',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.pazarlikci'),
        ),
    ]
